# Generated by Django 4.0.3 on 2022-06-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_stock_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_detail',
            name='area',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stock_detail',
            name='closing_month',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stock_detail',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='stock_detail',
            name='list_date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stock_detail',
            name='pagelink',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
