# Generated by Django 4.0.3 on 2022-06-06 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_alter_stock_detail_area_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock_Detail',
            new_name='StockDetail',
        ),
    ]
