# Generated by Django 4.0.3 on 2022-06-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_rename_stock_detail_stockdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdetail',
            name='chief',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='field',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='pagelink',
            field=models.TextField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='products',
            field=models.TextField(max_length=200),
        ),
    ]
