# Generated by Django 4.0.3 on 2022-06-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_alter_stockdetail_chief_alter_stockdetail_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdetail',
            name='area',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='closing_month',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='code',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='list_date',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='name',
            field=models.TextField(max_length=30),
        ),
    ]
