# Generated by Django 4.0.3 on 2022-06-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_alter_stockdetail_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdetail',
            name='id',
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='code',
            field=models.TextField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
