# Generated by Django 4.0.3 on 2022-06-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_remove_stockdetail_id_alter_stockdetail_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDetail2',
            fields=[
                ('name', models.TextField(max_length=30)),
                ('code', models.TextField(max_length=10, primary_key=True, serialize=False)),
                ('field', models.TextField(max_length=200)),
                ('products', models.TextField(max_length=200)),
                ('list_date', models.TextField(max_length=20)),
                ('closing_month', models.TextField(max_length=20)),
                ('chief', models.TextField(max_length=30)),
                ('pagelink', models.TextField(default='-', max_length=200)),
                ('area', models.TextField(max_length=50)),
            ],
        ),
    ]
