# Generated by Django 4.0.3 on 2022-06-09 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_stockdetail2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockDetail2',
        ),
    ]
